export const resultValues = {
    'error-login': {
        img: '/images/result_icon/rejection.svg',
        trigger: 'error-login',
        title: 'Вход не выполнен',
        text: 'Что-то пошло не так. Попробуйте еще раз',
        path: '/registrationPage',
        linkText: 'Повторить',
    },
    'error-user-exist': {
        img: '/images/result_icon/error.svg',
        trigger: 'error-user-exist',
        title: 'Данные не сохранились',
        text: 'Такой e-mail уже записан в системе. Попробуйте зарегистрироваться по другому e-mail',
        path: '/registrationPage/registration',
        linkText: 'Назад к регистрации',
    },
    'error': {
        img: '/images/result_icon/error.svg',
        trigger: 'error',
        title: 'Данные не сохранились',
        text: 'Что-то пошло не так и ваша регистрация не завершилась. Попробуйте еще раз.',
        path: '/registrationPage/registration',
        linkText: 'Повторить',
    },
    'success': {
        img: '/images/result_icon/success.svg',
        trigger: 'success',
        title: 'Регистрация успешна',
        text: 'Регистрация прошла успешно. Зайдите в приложение, используя свои e-mail и пароль.',
        path: '../..',
        linkText: 'Войти',
    },
    'success-change-password': {
        img: '/images/result_icon/success.svg',
        trigger: 'success-change-password',
        title: 'Пароль успешно изменен',
        text: 'Теперь можно войти в аккаунт, используя свой логин и новый пароль',
        path: '/registrationPage',
        linkText: 'Вход',
    },
    'error-change-password': {
        img: '/images/result_icon/error.svg',
        trigger: 'error-change-password',
        title: 'Данные не сохранились',
        text: 'Что-то пошло не так. Попробуйте ещё раз',
        path: '/change-password',
        linkText: 'Повторить',
    },
    emailError: {
        img: '/images/result_icon/error.svg',
        trigger: 'emailError',
        title: 'Такой e-mail не зарегистрирован',
        text: 'Мы не нашли в базе вашего e-mail. Попробуйте войти с другим e-mail.',
        path: '../..',
        linkText: 'Попробовать снова',
    },
    '500Error': {
        img: '/images/result_icon/wrongMan.svg',
        trigger: '500Error',
        title: 'Что-то пошло не так',
        text: 'Произошла ошибка, попробуйте отправить форму ещё раз.',
        path: '../..',
        linkText: 'Назад',
    }
};